### ISSUE TITLE
Fatal error: scard_connect(): Return value must be of type array|false, resource returned in Unknown on line 0

### ISSUE THREAD

**Issue by hanez** [pcsc-for-php/pcsc#5]
I switched to PHP 8.0.3 today for testing but it seems that the extension is not working there. In 7.4.16 everything works as expected. Does someone have an idea what could be wrong here?

```
hanez@jupiter [master] examples # php -dextension=pcsc simple.php

Warning: Module "PC/SC" is already loaded in Unknown on line 0
>> Create Context
resource(4) of type (PC/SC Context)
int(0)
string(15) "SCARD_S_SUCCESS"

>> Get Readers
array(2) {
  [0]=>
  string(38) "OMNIKEY CardMan (076B:5321) 5321 00 00"
  [1]=>
  string(38) "OMNIKEY CardMan (076B:5321) 5321 00 01"
}
int(0)
string(15) "SCARD_S_SUCCESS"

>> Select Reader
Using reader: OMNIKEY CardMan (076B:5321) 5321 00 01
int(0)
string(15) "SCARD_S_SUCCESS"

>> Connect to Card

Fatal error: scard_connect(): Return value must be of type array|false, resource returned in Unknown on line 0
```

**Comment by hanez** [comment]
Need to say that this *.stub.php stuff is very new to me...

**Comment by NattyNarwhal** [comment]
The function is [claiming to return an array or bool](https://github.com/pcsc-for-php/pcsc/blob/master/pcsc.stub.php#L28-L32), but it's [actually returning a resource](https://github.com/pcsc-for-php/pcsc/blob/master/pcsc.c#L612). Since the PHP type system can't express resource in the language, you have to do so in comments. The comment is there, but there language-level return specification is there, which I assume overrides the comment.

**Comment by hanez** [comment]
Okay, look like I need to go deeper into the stubs stuff... Tried a lot yesterday with different results but I think I am on the right way... Thank you very much!
