### ISSUE TITLE
help to get uid smartcard

### ISSUE THREAD

**Issue by meysamsalehi** [pcsc-for-php/pcsc#7]
hello 
i want to get uid smart card
But I do not know how to set $apdu ?
What is the required amount to receive uid?
example: $apdu = "";
Please help me set the appropriate value for the $ apdu variable instead
thanks.

cardreader : duali dragon

**Comment by hanez** [comment]
As I said in your previous issue, this is not a PC/SC related thing. I do not know anything about a uid. It must be documented in the documentation of your card application. I can not help you here because I do not know what kind of card you are using so I do not know the protocol your card application (the application on the card) has implemented. The PC/SC standard does not define APDU's, it just makes it possible to send and receive data (APDU's) to and from the card. It even is not related to your card reader.
